inherit_from: .rubocop_todo.yml

require:
  - rubocop-flexport
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6
  Exclude:
    - db/schema.rb
    - node_modules/**/*
    - vendor/bundle/**/*

Style/Documentation:
  Exclude:
    - db/migrate/*

Layout/LineLength:
  Max: 512
